### ISSUE TITLE
FYI: I'm using it :)

### ISSUE THREAD

**Issue by seeekr** [VoiceLayer/phoenix_cowboy2_example#1]
On the Elixir forums I think you had posted last year questioning if anyone is using these cowboy2 examples, and I'd just like to state that I do use them, at least this one, for phoenix. My use case is that I need gRPC support and am using https://github.com/tony612/grpc-elixir for that, which requires cowboy2.

In case there is an easier way by now I'd be grateful for updated information!

Thanks a bunch! Keep up the good work!

(EDIT: Can't get it to work so far though, probably using incompatible package versions somewhere by attempting to go with the latest version of cowboy (2.3), cowlib (2.1) and plug (1.5).)

**Comment by Gazler** [comment]
Glad to hear it. Phoenix master supports Cowboy 2 now, so you should just be able to update the versions in mix.exs for your application.

    def deps do
      {:phoenix, github: "phoenixframework/phoenix", override: true},
      ...
       {:cowboy, "~> 2.3"}
    end

**Comment by seeekr** [comment]
Thanks for the info! I found out in the meantime that the versions I tried were probably working just fine, but there was (and still exists) an issue in the grpc library currently.
